title: <center><font color="black">KEVIN PERDANA</font></center> # your name (or website title) here
logo: "/images/kevin.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  On Progress 
  <br><br>
  Certified Mobile Programmer by LSP Telematika, Jakarta | STTI Lecturer | Tanjungpinang Pos 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
